### ISSUE TITLE
Question about the memory use

### ISSUE THREAD

**Issue by yoyostudy** [RobinSmits/BAdam-Qwen#1]
Hi,

Thank you for your wonderful work.

I have a question about the memory requirements.

The `Qwen_1.5_1.8B-Chat` model has 1.8B parameters. In your code, you load the model in BF16 precision. Your experiment shows that the total memory requirement is 11-12GB.

However, based on the calculations from their paper, there seems to be a significant gap between the reported memory requirement (11-12GB) and the calculated requirement (3.4GB + 0.2GB + 0.6GB). 

I am not sure if this is the right place to ask, but I would like to have your help in understanding this discrepancy.

Here is a breakdown of the memory calculations:

  | Parameters | Gradient(FP32) | Optimizer(FP32) | Total
-- | -- | -- | -- | --
M | 2M(FP16), 4M(FP32) | 4M/D | 12M/D | 18M
Llama2-7B, D=32 | 13.4GB(FP16) | 0.8GB | 2.4GB | 21.8GB
Qwen1.5_1.8B-Chat, D=32 | 3.4GB(FP16) | 0.2GB | 0.6GB | 11-12GB

Thx,

**Comment by RobinSmits** [comment]
@yoyostudy Apologies for my late response. Tomorrow evening I have some spare time and will verify again with the script. I'll let you know the results.

**Comment by RobinSmits** [comment]
@yoyostudy I did some more testruns with the notebook. When the model is just loaded into GPU memory it uses around 4.6 GB of GPU RAM.

When I start training the model - with max sequence length of 1024 and a batch size of 2 - the used GPU Memory hovers around 10 GB.

I don't think the values are a discrepancy between the paper and reality. The memory calculations they provide are general guidelines I presume but the real values can slightly change based on different model architectures. When actually training the model the memory consumption will increase depending on the used batch size.

I will make some minor updates in my notebook and the description provided and will publish those in the coming days.

If you still have some doubts about the values you notice when training with it I would suggest to contact the researchers that created the BAdam method.
